[package]
authors = ["Sven Kanoldt <sven@d34dl0ck.me>"]
name = "http-pest"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
pest = "2.1"
pest_derive = "2.1"

from-pest = "0.3"
pest-ast = "0.3"
